//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ACCESS-AUTHORISATIONS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACCESS-AUTHORISATIONS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ACCESS-AUTHORISATION" type="{}ACCESS-AUTHORISATION" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACCESS-AUTHORISATIONS", propOrder = {
    "accessauthorisation"
})
public class ACCESSAUTHORISATIONS {

    @XmlElement(name = "ACCESS-AUTHORISATION")
    protected List<ACCESSAUTHORISATION> accessauthorisation;

    /**
     * Gets the value of the accessauthorisation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessauthorisation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACCESSAUTHORISATION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ACCESSAUTHORISATION }
     * 
     * 
     */
    public List<ACCESSAUTHORISATION> getACCESSAUTHORISATION() {
        if (accessauthorisation == null) {
            accessauthorisation = new ArrayList<ACCESSAUTHORISATION>();
        }
        return this.accessauthorisation;
    }

}
