//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BRANCH complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BRANCH"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}IB-ELEMENT"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *         &lt;element name="IF" type="{}IF"/&gt;
 *         &lt;element name="ELSEIF" type="{}ELSEIF" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ELSE" type="{}ELSE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="testResult" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="cyclic" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BRANCH", propOrder = {
    "desc",
    "_if",
    "elseif",
    "_else"
})
public class BRANCH
    extends IBELEMENT
{

    @XmlElement(name = "DESC")
    protected String desc;
    @XmlElement(name = "IF", required = true)
    protected IF _if;
    @XmlElement(name = "ELSEIF")
    protected List<ELSEIF> elseif;
    @XmlElement(name = "ELSE")
    protected ELSE _else;
    @XmlAttribute(name = "testResult")
    protected Boolean testResult;
    @XmlAttribute(name = "cyclic")
    protected Boolean cyclic;

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link IF }
     *     
     */
    public IF getIF() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link IF }
     *     
     */
    public void setIF(IF value) {
        this._if = value;
    }

    /**
     * Gets the value of the elseif property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elseif property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getELSEIF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ELSEIF }
     * 
     * 
     */
    public List<ELSEIF> getELSEIF() {
        if (elseif == null) {
            elseif = new ArrayList<ELSEIF>();
        }
        return this.elseif;
    }

    /**
     * Gets the value of the else property.
     * 
     * @return
     *     possible object is
     *     {@link ELSE }
     *     
     */
    public ELSE getELSE() {
        return _else;
    }

    /**
     * Sets the value of the else property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELSE }
     *     
     */
    public void setELSE(ELSE value) {
        this._else = value;
    }

    /**
     * Gets the value of the testResult property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTestResult() {
        return testResult;
    }

    /**
     * Sets the value of the testResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTestResult(Boolean value) {
        this.testResult = value;
    }

    /**
     * Gets the value of the cyclic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCyclic() {
        return cyclic;
    }

    /**
     * Sets the value of the cyclic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCyclic(Boolean value) {
        this.cyclic = value;
    }

}
