//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BYTES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BYTES"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BYTE-0" type="{}BYTE"/&gt;
 *         &lt;element name="BYTE-1" type="{}BYTE"/&gt;
 *         &lt;element name="BYTE-2" type="{}BYTE"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BYTES", propOrder = {
    "byte0",
    "byte1",
    "byte2"
})
public class BYTES {

    @XmlElement(name = "BYTE-0", required = true)
    protected String byte0;
    @XmlElement(name = "BYTE-1", required = true)
    protected String byte1;
    @XmlElement(name = "BYTE-2", required = true)
    protected String byte2;

    /**
     * Gets the value of the byte0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBYTE0() {
        return byte0;
    }

    /**
     * Sets the value of the byte0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBYTE0(String value) {
        this.byte0 = value;
    }

    /**
     * Gets the value of the byte1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBYTE1() {
        return byte1;
    }

    /**
     * Sets the value of the byte1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBYTE1(String value) {
        this.byte1 = value;
    }

    /**
     * Gets the value of the byte2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBYTE2() {
        return byte2;
    }

    /**
     * Sets the value of the byte2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBYTE2(String value) {
        this.byte2 = value;
    }

}
