//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CUSTOMER-ADJUSTMENTS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUSTOMER-ADJUSTMENTS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ADJUSTMENTS" type="{}ADJUSTMENTS" minOccurs="0"/&gt;
 *         &lt;element name="BLOCKING-DTCS" type="{}DTCS" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUSTOMER-ADJUSTMENTS", propOrder = {
    "adjustments",
    "blockingdtcs"
})
public class CUSTOMERADJUSTMENTS {

    @XmlElement(name = "ADJUSTMENTS")
    protected ADJUSTMENTS adjustments;
    @XmlElement(name = "BLOCKING-DTCS")
    protected DTCS blockingdtcs;

    /**
     * Gets the value of the adjustments property.
     * 
     * @return
     *     possible object is
     *     {@link ADJUSTMENTS }
     *     
     */
    public ADJUSTMENTS getADJUSTMENTS() {
        return adjustments;
    }

    /**
     * Sets the value of the adjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADJUSTMENTS }
     *     
     */
    public void setADJUSTMENTS(ADJUSTMENTS value) {
        this.adjustments = value;
    }

    /**
     * Gets the value of the blockingdtcs property.
     * 
     * @return
     *     possible object is
     *     {@link DTCS }
     *     
     */
    public DTCS getBLOCKINGDTCS() {
        return blockingdtcs;
    }

    /**
     * Sets the value of the blockingdtcs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DTCS }
     *     
     */
    public void setBLOCKINGDTCS(DTCS value) {
        this.blockingdtcs = value;
    }

}
