//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DEVICE-STEP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DEVICE-STEP"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}STEP-ELEMENT"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *         &lt;element name="TIS" type="{}TIS" minOccurs="0"/&gt;
 *         &lt;element name="DEVICE-PARAMETERS" type="{}DEVICE-PARAMETERS" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DEVICE-STEP", propOrder = {
    "desc",
    "tis",
    "deviceparameters"
})
public class DEVICESTEP
    extends STEPELEMENT
{

    @XmlElement(name = "DESC")
    protected String desc;
    @XmlElement(name = "TIS")
    protected TIS tis;
    @XmlElement(name = "DEVICE-PARAMETERS")
    protected DEVICEPARAMETERS deviceparameters;

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the tis property.
     * 
     * @return
     *     possible object is
     *     {@link TIS }
     *     
     */
    public TIS getTIS() {
        return tis;
    }

    /**
     * Sets the value of the tis property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIS }
     *     
     */
    public void setTIS(TIS value) {
        this.tis = value;
    }

    /**
     * Gets the value of the deviceparameters property.
     * 
     * @return
     *     possible object is
     *     {@link DEVICEPARAMETERS }
     *     
     */
    public DEVICEPARAMETERS getDEVICEPARAMETERS() {
        return deviceparameters;
    }

    /**
     * Sets the value of the deviceparameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DEVICEPARAMETERS }
     *     
     */
    public void setDEVICEPARAMETERS(DEVICEPARAMETERS value) {
        this.deviceparameters = value;
    }

}
