//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DEVICE-BLOCK-TYPE.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DEVICE-BLOCK-TYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="command"/&gt;
 *     &lt;enumeration value="movement"/&gt;
 *     &lt;enumeration value="state"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "DEVICE-BLOCK-TYPE")
@XmlEnum
public enum DEVICEBLOCKTYPE {

    @XmlEnumValue("command")
    COMMAND("command"),
    @XmlEnumValue("movement")
    MOVEMENT("movement"),
    @XmlEnumValue("state")
    STATE("state");
    private final String value;

    DEVICEBLOCKTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DEVICEBLOCKTYPE fromValue(String v) {
        for (DEVICEBLOCKTYPE c: DEVICEBLOCKTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
