//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DIAGNOSTIC-INFO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DIAGNOSTIC-INFO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *         &lt;element name="DIAG-PROTOCOL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TRANSPORT-PROTOCOL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ECU-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PDX" type="{}PDX" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAGNOSTIC-INFO", propOrder = {
    "desc",
    "diagprotocol",
    "transportprotocol",
    "ecuid",
    "pdx"
})
public class DIAGNOSTICINFO {

    @XmlElement(name = "DESC")
    protected String desc;
    @XmlElement(name = "DIAG-PROTOCOL")
    protected String diagprotocol;
    @XmlElement(name = "TRANSPORT-PROTOCOL")
    protected String transportprotocol;
    @XmlElement(name = "ECU-ID")
    protected String ecuid;
    @XmlElement(name = "PDX")
    protected PDX pdx;

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the diagprotocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDIAGPROTOCOL() {
        return diagprotocol;
    }

    /**
     * Sets the value of the diagprotocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDIAGPROTOCOL(String value) {
        this.diagprotocol = value;
    }

    /**
     * Gets the value of the transportprotocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRANSPORTPROTOCOL() {
        return transportprotocol;
    }

    /**
     * Sets the value of the transportprotocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRANSPORTPROTOCOL(String value) {
        this.transportprotocol = value;
    }

    /**
     * Gets the value of the ecuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECUID() {
        return ecuid;
    }

    /**
     * Sets the value of the ecuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECUID(String value) {
        this.ecuid = value;
    }

    /**
     * Gets the value of the pdx property.
     * 
     * @return
     *     possible object is
     *     {@link PDX }
     *     
     */
    public PDX getPDX() {
        return pdx;
    }

    /**
     * Sets the value of the pdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDX }
     *     
     */
    public void setPDX(PDX value) {
        this.pdx = value;
    }

}
