//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for DIAG-PARAMETER complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DIAG-PARAMETER"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LONG-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MESSAGE-TYPE" type="{}MESSAGE-TYPE" minOccurs="0"/&gt;
 *         &lt;element name="RESPONSE-SHORT-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PATH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DATATYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VALUE-PROXY" type="{}VALUE-PROXY" minOccurs="0"/&gt;
 *         &lt;element name="DISPLAYUNIT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAG-PARAMETER", propOrder = {
    "longname",
    "shortname",
    "messagetype",
    "responseshortname",
    "path",
    "datatype",
    "valueproxy",
    "displayunit"
})
public class DIAGPARAMETER {

    @XmlElement(name = "LONG-NAME")
    protected String longname;
    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "MESSAGE-TYPE")
    @XmlSchemaType(name = "string")
    protected MESSAGETYPE messagetype;
    @XmlElement(name = "RESPONSE-SHORT-NAME")
    protected String responseshortname;
    @XmlElement(name = "PATH")
    protected String path;
    @XmlElement(name = "DATATYPE")
    protected String datatype;
    @XmlElement(name = "VALUE-PROXY")
    protected VALUEPROXY valueproxy;
    @XmlElement(name = "DISPLAYUNIT")
    protected String displayunit;

    /**
     * Gets the value of the longname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLONGNAME() {
        return longname;
    }

    /**
     * Sets the value of the longname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLONGNAME(String value) {
        this.longname = value;
    }

    /**
     * Gets the value of the shortname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSHORTNAME(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the messagetype property.
     *
     * @return
     *     possible object is
     *     {@link MESSAGETYPE }
     *
     */
    public MESSAGETYPE getMESSAGETYPE() {
        return messagetype;
    }

    /**
     * Sets the value of the messagetype property.
     *
     * @param value
     *     allowed object is
     *     {@link MESSAGETYPE }
     *
     */
    public void setMESSAGETYPE(MESSAGETYPE value) {
        this.messagetype = value;
    }

    /**
     * Gets the value of the responseshortname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRESPONSESHORTNAME() {
        return responseshortname;
    }

    /**
     * Sets the value of the responseshortname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRESPONSESHORTNAME(String value) {
        this.responseshortname = value;
    }

    /**
     * Gets the value of the path property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPATH() {
        return path;
    }

    /**
     * Sets the value of the path property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPATH(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the datatype property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDATATYPE() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDATATYPE(String value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the valueproxy property.
     *
     * @return
     *     possible object is
     *     {@link VALUEPROXY }
     *
     */
    public VALUEPROXY getVALUEPROXY() {
        return valueproxy;
    }

    /**
     * Sets the value of the valueproxy property.
     *
     * @param value
     *     allowed object is
     *     {@link VALUEPROXY }
     *
     */
    public void setVALUEPROXY(VALUEPROXY value) {
        this.valueproxy = value;
    }

    /**
     * Gets the value of the displayunit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDISPLAYUNIT() {
        return displayunit;
    }

    /**
     * Sets the value of the displayunit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDISPLAYUNIT(String value) {
        this.displayunit = value;
    }

}
