//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOC-REVISION complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DOC-REVISION"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VERSION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DATE" type="{}DATE"/&gt;
 *         &lt;element name="AUTHOR-REF" type="{}REFERENCE"/&gt;
 *         &lt;element name="CHANGE" type="{}DESC"/&gt;
 *         &lt;element name="TOOL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOC-REVISION", propOrder = {
    "version",
    "date",
    "authorref",
    "change",
    "tool"
})
public class DOCREVISION {

    @XmlElement(name = "VERSION", required = true)
    protected String version;
    @XmlElement(name = "DATE", required = true)
    protected String date;
    @XmlElement(name = "AUTHOR-REF", required = true)
    protected REFERENCE authorref;
    @XmlElement(name = "CHANGE", required = true)
    protected String change;
    @XmlElement(name = "TOOL")
    protected String tool;

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVERSION(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the date property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDATE(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the authorref property.
     *
     * @return
     *     possible object is
     *     {@link REFERENCE }
     *
     */
    public REFERENCE getAUTHORREF() {
        return authorref;
    }

    /**
     * Sets the value of the authorref property.
     *
     * @param value
     *     allowed object is
     *     {@link REFERENCE }
     *
     */
    public void setAUTHORREF(REFERENCE value) {
        this.authorref = value;
    }

    /**
     * Gets the value of the change property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCHANGE() {
        return change;
    }

    /**
     * Sets the value of the change property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCHANGE(String value) {
        this.change = value;
    }

    /**
     * Gets the value of the tool property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTOOL() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTOOL(String value) {
        this.tool = value;
    }

}
