//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DOCUMENT-INFO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DOCUMENT-INFO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CONTACTS" type="{}CONTACTS"/&gt;
 *         &lt;element name="DOC-REVISIONS" type="{}DOC-REVISIONS"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DOCUMENT-INFO", propOrder = {
    "contacts",
    "docrevisions"
})
public class DOCUMENTINFO {

    @XmlElement(name = "CONTACTS", required = true)
    protected CONTACTS contacts;
    @XmlElement(name = "DOC-REVISIONS", required = true)
    protected DOCREVISIONS docrevisions;

    /**
     * Gets the value of the contacts property.
     *
     * @return
     *     possible object is
     *     {@link CONTACTS }
     *
     */
    public CONTACTS getCONTACTS() {
        return contacts;
    }

    /**
     * Sets the value of the contacts property.
     *
     * @param value
     *     allowed object is
     *     {@link CONTACTS }
     *
     */
    public void setCONTACTS(CONTACTS value) {
        this.contacts = value;
    }

    /**
     * Gets the value of the docrevisions property.
     *
     * @return
     *     possible object is
     *     {@link DOCREVISIONS }
     *
     */
    public DOCREVISIONS getDOCREVISIONS() {
        return docrevisions;
    }

    /**
     * Sets the value of the docrevisions property.
     *
     * @param value
     *     allowed object is
     *     {@link DOCREVISIONS }
     *
     */
    public void setDOCREVISIONS(DOCREVISIONS value) {
        this.docrevisions = value;
    }

}
