//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DTC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DTC"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DTC-TI" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DFCC-TEXT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DTC", propOrder = {
    "dtcti",
    "dfcctext"
})
public class DTC {

    @XmlElement(name = "DTC-TI", required = true)
    protected String dtcti;
    @XmlElement(name = "DFCC-TEXT", required = true)
    protected String dfcctext;

    /**
     * Gets the value of the dtcti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDTCTI() {
        return dtcti;
    }

    /**
     * Sets the value of the dtcti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDTCTI(String value) {
        this.dtcti = value;
    }

    /**
     * Gets the value of the dfcctext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFCCTEXT() {
        return dfcctext;
    }

    /**
     * Sets the value of the dfcctext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFCCTEXT(String value) {
        this.dfcctext = value;
    }

}
