//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ECU complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ECU"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ECU-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VARIANTS" type="{}VARIANTS" minOccurs="0"/&gt;
 *         &lt;element name="SECURITY-PROPERTY" type="{}PARAMETER" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECU", propOrder = {
    "name",
    "ecuid",
    "variants",
    "securityproperty"
})
public class ECU {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "ECU-ID")
    protected String ecuid;
    @XmlElement(name = "VARIANTS")
    protected VARIANTS variants;
    @XmlElement(name = "SECURITY-PROPERTY", required = true)
    protected List<PARAMETER> securityproperty;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the ecuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECUID() {
        return ecuid;
    }

    /**
     * Sets the value of the ecuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECUID(String value) {
        this.ecuid = value;
    }

    /**
     * Gets the value of the variants property.
     * 
     * @return
     *     possible object is
     *     {@link VARIANTS }
     *     
     */
    public VARIANTS getVARIANTS() {
        return variants;
    }

    /**
     * Sets the value of the variants property.
     * 
     * @param value
     *     allowed object is
     *     {@link VARIANTS }
     *     
     */
    public void setVARIANTS(VARIANTS value) {
        this.variants = value;
    }

    /**
     * Gets the value of the securityproperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityproperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSECURITYPROPERTY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PARAMETER }
     * 
     * 
     */
    public List<PARAMETER> getSECURITYPROPERTY() {
        if (securityproperty == null) {
            securityproperty = new ArrayList<PARAMETER>();
        }
        return this.securityproperty;
    }

}
