//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ENVIRONMENT complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ENVIRONMENT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PRE-CONDITIONS" type="{}PRE-CONDITIONS" minOccurs="0"/&gt;
 *         &lt;element name="DEPENDENCIES" type="{}DEPENDENCIES" minOccurs="0"/&gt;
 *         &lt;element name="REPAIR-DEPENDENCIES" type="{}REPAIR-DEPENDENCIES" minOccurs="0"/&gt;
 *         &lt;element name="ACCESS-AUTHORISATIONS" type="{}ACCESS-AUTHORISATIONS" minOccurs="0"/&gt;
 *         &lt;element name="PRODUCTION-MODES" type="{}PRODUCTION-MODES" minOccurs="0"/&gt;
 *         &lt;element name="TRANSPORT-MODE" type="{}DESC" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ENVIRONMENT", propOrder = {
    "preconditions",
    "dependencies",
    "repairdependencies",
    "accessauthorisations",
    "productionmodes",
    "transportmode"
})
public class ENVIRONMENT {

    @XmlElement(name = "PRE-CONDITIONS")
    protected PRECONDITIONS preconditions;
    @XmlElement(name = "DEPENDENCIES")
    protected DEPENDENCIES dependencies;
    @XmlElement(name = "REPAIR-DEPENDENCIES")
    protected REPAIRDEPENDENCIES repairdependencies;
    @XmlElement(name = "ACCESS-AUTHORISATIONS")
    protected ACCESSAUTHORISATIONS accessauthorisations;
    @XmlElement(name = "PRODUCTION-MODES")
    protected PRODUCTIONMODES productionmodes;
    @XmlElement(name = "TRANSPORT-MODE")
    protected String transportmode;

    /**
     * Gets the value of the preconditions property.
     *
     * @return
     *     possible object is
     *     {@link PRECONDITIONS }
     *
     */
    public PRECONDITIONS getPRECONDITIONS() {
        return preconditions;
    }

    /**
     * Sets the value of the preconditions property.
     *
     * @param value
     *     allowed object is
     *     {@link PRECONDITIONS }
     *
     */
    public void setPRECONDITIONS(PRECONDITIONS value) {
        this.preconditions = value;
    }

    /**
     * Gets the value of the dependencies property.
     *
     * @return
     *     possible object is
     *     {@link DEPENDENCIES }
     *
     */
    public DEPENDENCIES getDEPENDENCIES() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     *
     * @param value
     *     allowed object is
     *     {@link DEPENDENCIES }
     *
     */
    public void setDEPENDENCIES(DEPENDENCIES value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the repairdependencies property.
     *
     * @return
     *     possible object is
     *     {@link REPAIRDEPENDENCIES }
     *
     */
    public REPAIRDEPENDENCIES getREPAIRDEPENDENCIES() {
        return repairdependencies;
    }

    /**
     * Sets the value of the repairdependencies property.
     *
     * @param value
     *     allowed object is
     *     {@link REPAIRDEPENDENCIES }
     *
     */
    public void setREPAIRDEPENDENCIES(REPAIRDEPENDENCIES value) {
        this.repairdependencies = value;
    }

    /**
     * Gets the value of the accessauthorisations property.
     *
     * @return
     *     possible object is
     *     {@link ACCESSAUTHORISATIONS }
     *
     */
    public ACCESSAUTHORISATIONS getACCESSAUTHORISATIONS() {
        return accessauthorisations;
    }

    /**
     * Sets the value of the accessauthorisations property.
     *
     * @param value
     *     allowed object is
     *     {@link ACCESSAUTHORISATIONS }
     *
     */
    public void setACCESSAUTHORISATIONS(ACCESSAUTHORISATIONS value) {
        this.accessauthorisations = value;
    }

    /**
     * Gets the value of the productionmodes property.
     *
     * @return
     *     possible object is
     *     {@link PRODUCTIONMODES }
     *
     */
    public PRODUCTIONMODES getPRODUCTIONMODES() {
        return productionmodes;
    }

    /**
     * Sets the value of the productionmodes property.
     *
     * @param value
     *     allowed object is
     *     {@link PRODUCTIONMODES }
     *
     */
    public void setPRODUCTIONMODES(PRODUCTIONMODES value) {
        this.productionmodes = value;
    }

    /**
     * Gets the value of the transportmode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTRANSPORTMODE() {
        return transportmode;
    }

    /**
     * Sets the value of the transportmode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTRANSPORTMODE(String value) {
        this.transportmode = value;
    }

}
