//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IB-DESCRIPTION complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="IB-DESCRIPTION"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IB-VARIANTS" type="{}IB-VARIANTS" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="VALIDITIES" type="{}VALIDITIES"/&gt;
 *           &lt;element name="VALIDITIES-REF" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="OBJECTIVES" type="{}OBJECTIVES" minOccurs="0"/&gt;
 *         &lt;element name="IBNZ" type="{}IBNZ" minOccurs="0"/&gt;
 *         &lt;element name="SLAVES" type="{}SLAVES" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IB-DESCRIPTION", propOrder = {
    "ibvariants",
    "validities",
    "validitiesref",
    "objectives",
    "ibnz",
    "slaves"
})
public class IBDESCRIPTION {

    @XmlElement(name = "IB-VARIANTS")
    protected IBVARIANTS ibvariants;
    @XmlElement(name = "VALIDITIES")
    protected VALIDITIES validities;
    @XmlElement(name = "VALIDITIES-REF")
    protected String validitiesref;
    @XmlElement(name = "OBJECTIVES")
    protected OBJECTIVES objectives;
    @XmlElement(name = "IBNZ")
    protected IBNZ ibnz;
    @XmlElement(name = "SLAVES")
    protected SLAVES slaves;

    /**
     * Gets the value of the ibvariants property.
     *
     * @return
     *     possible object is
     *     {@link IBVARIANTS }
     *
     */
    public IBVARIANTS getIBVARIANTS() {
        return ibvariants;
    }

    /**
     * Sets the value of the ibvariants property.
     *
     * @param value
     *     allowed object is
     *     {@link IBVARIANTS }
     *
     */
    public void setIBVARIANTS(IBVARIANTS value) {
        this.ibvariants = value;
    }

    /**
     * Gets the value of the validities property.
     *
     * @return
     *     possible object is
     *     {@link VALIDITIES }
     *
     */
    public VALIDITIES getVALIDITIES() {
        return validities;
    }

    /**
     * Sets the value of the validities property.
     *
     * @param value
     *     allowed object is
     *     {@link VALIDITIES }
     *
     */
    public void setVALIDITIES(VALIDITIES value) {
        this.validities = value;
    }

    /**
     * Gets the value of the validitiesref property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVALIDITIESREF() {
        return validitiesref;
    }

    /**
     * Sets the value of the validitiesref property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVALIDITIESREF(String value) {
        this.validitiesref = value;
    }

    /**
     * Gets the value of the objectives property.
     *
     * @return
     *     possible object is
     *     {@link OBJECTIVES }
     *
     */
    public OBJECTIVES getOBJECTIVES() {
        return objectives;
    }

    /**
     * Sets the value of the objectives property.
     *
     * @param value
     *     allowed object is
     *     {@link OBJECTIVES }
     *
     */
    public void setOBJECTIVES(OBJECTIVES value) {
        this.objectives = value;
    }

    /**
     * Gets the value of the ibnz property.
     *
     * @return
     *     possible object is
     *     {@link IBNZ }
     *
     */
    public IBNZ getIBNZ() {
        return ibnz;
    }

    /**
     * Sets the value of the ibnz property.
     *
     * @param value
     *     allowed object is
     *     {@link IBNZ }
     *
     */
    public void setIBNZ(IBNZ value) {
        this.ibnz = value;
    }

    /**
     * Gets the value of the slaves property.
     *
     * @return
     *     possible object is
     *     {@link SLAVES }
     *
     */
    public SLAVES getSLAVES() {
        return slaves;
    }

    /**
     * Sets the value of the slaves property.
     *
     * @param value
     *     allowed object is
     *     {@link SLAVES }
     *
     */
    public void setSLAVES(SLAVES value) {
        this.slaves = value;
    }

}
