//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for IB-ELEMENT complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="IB-ELEMENT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}IB-IDENTIFIABLE"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NAME_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IB-ELEMENT", propOrder = {
    "name",
    "nameen"
})
@XmlSeeAlso({
    IBLIBRARY.class,
    IB1 .class,
    CONTACT.class,
    BLOCK.class,
    DEVICEBLOCK.class,
    BRANCH.class,
    IF.class,
    ELSEIF.class,
    IBVARIANT.class,
    IBOPERATION.class,
    SLAVE.class,
    PRODUCTIONMODE.class,
    ACCESSAUTHORISATION.class,
    PROCEDURE.class,
    GROUP.class,
    SWITCH.class,
    CASE.class
})
public class IBELEMENT
    extends IBIDENTIFIABLE
{

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "NAME_EN")
    protected String nameen;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameen property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNAMEEN() {
        return nameen;
    }

    /**
     * Sets the value of the nameen property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNAMEEN(String value) {
        this.nameen = value;
    }

    /**
     * Gets the value of the path property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPath(String value) {
        this.path = value;
    }

}
