//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for IB-LIBRARY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IB-LIBRARY"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}IB-ELEMENT"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RELEASE-DATE" type="{}DATE" minOccurs="0"/&gt;
 *         &lt;element name="DOC-INFO" type="{}DOCUMENT-INFO"/&gt;
 *         &lt;element name="BLOCK" type="{}BLOCK" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IB-LIBRARY", propOrder = {
    "releasedate",
    "docinfo",
    "block"
})
public class IBLIBRARY
    extends IBELEMENT
{

    @XmlElement(name = "RELEASE-DATE")
    protected String releasedate;
    @XmlElement(name = "DOC-INFO", required = true)
    protected DOCUMENTINFO docinfo;
    @XmlElement(name = "BLOCK")
    protected List<BLOCK> block;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the releasedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRELEASEDATE() {
        return releasedate;
    }

    /**
     * Sets the value of the releasedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRELEASEDATE(String value) {
        this.releasedate = value;
    }

    /**
     * Gets the value of the docinfo property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTINFO }
     *     
     */
    public DOCUMENTINFO getDOCINFO() {
        return docinfo;
    }

    /**
     * Sets the value of the docinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTINFO }
     *     
     */
    public void setDOCINFO(DOCUMENTINFO value) {
        this.docinfo = value;
    }

    /**
     * Gets the value of the block property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the block property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBLOCK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BLOCK }
     * 
     * 
     */
    public List<BLOCK> getBLOCK() {
        if (block == null) {
            block = new ArrayList<BLOCK>();
        }
        return this.block;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
