//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IDENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IDENT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="S42-ATTRIBUTE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BGONLINE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="COMMENT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IDENT", propOrder = {
    "name",
    "s42ATTRIBUTE",
    "bgonline",
    "did",
    "comment"
})
public class IDENT {

    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "S42-ATTRIBUTE")
    protected String s42ATTRIBUTE;
    @XmlElement(name = "BGONLINE")
    protected String bgonline;
    @XmlElement(name = "DID")
    protected String did;
    @XmlElement(name = "COMMENT")
    protected String comment;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the s42ATTRIBUTE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getS42ATTRIBUTE() {
        return s42ATTRIBUTE;
    }

    /**
     * Sets the value of the s42ATTRIBUTE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setS42ATTRIBUTE(String value) {
        this.s42ATTRIBUTE = value;
    }

    /**
     * Gets the value of the bgonline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBGONLINE() {
        return bgonline;
    }

    /**
     * Sets the value of the bgonline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBGONLINE(String value) {
        this.bgonline = value;
    }

    /**
     * Gets the value of the did property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDID() {
        return did;
    }

    /**
     * Sets the value of the did property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDID(String value) {
        this.did = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMENT() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMENT(String value) {
        this.comment = value;
    }

}
