//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for IMPORT-ELEMENT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IMPORT-ELEMENT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}IB-IDENTIFIABLE"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ADDITIONAL-NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ADDITIONAL-NAME_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="import-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IMPORT-ELEMENT", propOrder = {
    "additionalname",
    "additionalnameen"
})
public class IMPORTELEMENT
    extends IBIDENTIFIABLE
{

    @XmlElement(name = "ADDITIONAL-NAME")
    protected String additionalname;
    @XmlElement(name = "ADDITIONAL-NAME_EN")
    protected String additionalnameen;
    @XmlAttribute(name = "import-id", required = true)
    protected String importId;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * Gets the value of the additionalname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDITIONALNAME() {
        return additionalname;
    }

    /**
     * Sets the value of the additionalname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDITIONALNAME(String value) {
        this.additionalname = value;
    }

    /**
     * Gets the value of the additionalnameen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDITIONALNAMEEN() {
        return additionalnameen;
    }

    /**
     * Sets the value of the additionalnameen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDITIONALNAMEEN(String value) {
        this.additionalnameen = value;
    }

    /**
     * Gets the value of the importId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportId() {
        return importId;
    }

    /**
     * Sets the value of the importId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportId(String value) {
        this.importId = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
