//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LOOP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LOOP"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}LOOP-ELEMENT"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BLOCKS" type="{}LOOP-BLOCKS" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LOOP", propOrder = {
    "blocks"
})
public class LOOP
    extends LOOPELEMENT
{

    @XmlElement(name = "BLOCKS")
    protected LOOPBLOCKS blocks;

    /**
     * Gets the value of the blocks property.
     * 
     * @return
     *     possible object is
     *     {@link LOOPBLOCKS }
     *     
     */
    public LOOPBLOCKS getBLOCKS() {
        return blocks;
    }

    /**
     * Sets the value of the blocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link LOOPBLOCKS }
     *     
     */
    public void setBLOCKS(LOOPBLOCKS value) {
        this.blocks = value;
    }

}
