//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for LOOP-ELEMENT complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LOOP-ELEMENT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}IB-IDENTIFIABLE"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NAME_EN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *         &lt;element name="POLLINTERVALL" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="TIMEOUT" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LOOP-ELEMENT", propOrder = {
    "name",
    "nameen",
    "desc",
    "pollintervall",
    "timeout"
})
@XmlSeeAlso({
    LOOP.class
})
public class LOOPELEMENT
    extends IBIDENTIFIABLE
{

    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "NAME_EN")
    protected String nameen;
    @XmlElement(name = "DESC")
    protected String desc;
    @XmlElement(name = "POLLINTERVALL")
    protected BigInteger pollintervall;
    @XmlElement(name = "TIMEOUT")
    protected BigInteger timeout;
    @XmlAttribute(name = "path")
    protected String path;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameen property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNAMEEN() {
        return nameen;
    }

    /**
     * Sets the value of the nameen property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNAMEEN(String value) {
        this.nameen = value;
    }

    /**
     * Gets the value of the desc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDESC(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the pollintervall property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getPOLLINTERVALL() {
        return pollintervall;
    }

    /**
     * Sets the value of the pollintervall property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setPOLLINTERVALL(BigInteger value) {
        this.pollintervall = value;
    }

    /**
     * Gets the value of the timeout property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getTIMEOUT() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setTIMEOUT(BigInteger value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the path property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPath(String value) {
        this.path = value;
    }

}
