//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IBLIBRARY_QNAME = new QName("", "IB-LIBRARY");
    private final static QName _IB1_QNAME = new QName("", "IB-1");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IBLIBRARY }
     *
     */
    public IBLIBRARY createIBLIBRARY() {
        return new IBLIBRARY();
    }

    /**
     * Create an instance of {@link IB1 }
     *
     */
    public IB1 createIB1() {
        return new IB1();
    }

    /**
     * Create an instance of {@link TIS }
     *
     */
    public TIS createTIS() {
        return new TIS();
    }

    /**
     * Create an instance of {@link CONTACT }
     *
     */
    public CONTACT createCONTACT() {
        return new CONTACT();
    }

    /**
     * Create an instance of {@link IMPORTREF }
     *
     */
    public IMPORTREF createIMPORTREF() {
        return new IMPORTREF();
    }

    /**
     * Create an instance of {@link DOCUMENTINFO }
     *
     */
    public DOCUMENTINFO createDOCUMENTINFO() {
        return new DOCUMENTINFO();
    }

    /**
     * Create an instance of {@link CONTACTS }
     *
     */
    public CONTACTS createCONTACTS() {
        return new CONTACTS();
    }

    /**
     * Create an instance of {@link IMPORTREFS }
     *
     */
    public IMPORTREFS createIMPORTREFS() {
        return new IMPORTREFS();
    }

    /**
     * Create an instance of {@link DOCREVISIONS }
     *
     */
    public DOCREVISIONS createDOCREVISIONS() {
        return new DOCREVISIONS();
    }

    /**
     * Create an instance of {@link BLOCK }
     *
     */
    public BLOCK createBLOCK() {
        return new BLOCK();
    }

    /**
     * Create an instance of {@link DEVICEBLOCK }
     *
     */
    public DEVICEBLOCK createDEVICEBLOCK() {
        return new DEVICEBLOCK();
    }

    /**
     * Create an instance of {@link DEVICESTEPS }
     *
     */
    public DEVICESTEPS createDEVICESTEPS() {
        return new DEVICESTEPS();
    }

    /**
     * Create an instance of {@link EXTERNALPARAMETERS }
     *
     */
    public EXTERNALPARAMETERS createEXTERNALPARAMETERS() {
        return new EXTERNALPARAMETERS();
    }

    /**
     * Create an instance of {@link EXTERNALPARAMETER }
     *
     */
    public EXTERNALPARAMETER createEXTERNALPARAMETER() {
        return new EXTERNALPARAMETER();
    }

    /**
     * Create an instance of {@link OPERATIONS }
     *
     */
    public OPERATIONS createOPERATIONS() {
        return new OPERATIONS();
    }

    /**
     * Create an instance of {@link TAGS }
     *
     */
    public TAGS createTAGS() {
        return new TAGS();
    }

    /**
     * Create an instance of {@link CONDITIONS }
     *
     */
    public CONDITIONS createCONDITIONS() {
        return new CONDITIONS();
    }

    /**
     * Create an instance of {@link VARIANTS }
     *
     */
    public VARIANTS createVARIANTS() {
        return new VARIANTS();
    }

    /**
     * Create an instance of {@link BLOCKDEPENDENCIES }
     *
     */
    public BLOCKDEPENDENCIES createBLOCKDEPENDENCIES() {
        return new BLOCKDEPENDENCIES();
    }

    /**
     * Create an instance of {@link PARAMETERS }
     *
     */
    public PARAMETERS createPARAMETERS() {
        return new PARAMETERS();
    }

    /**
     * Create an instance of {@link HMIPARAMETERS }
     *
     */
    public HMIPARAMETERS createHMIPARAMETERS() {
        return new HMIPARAMETERS();
    }

    /**
     * Create an instance of {@link DEVICEPARAMETERS }
     *
     */
    public DEVICEPARAMETERS createDEVICEPARAMETERS() {
        return new DEVICEPARAMETERS();
    }

    /**
     * Create an instance of {@link DATAPARAMETERS }
     *
     */
    public DATAPARAMETERS createDATAPARAMETERS() {
        return new DATAPARAMETERS();
    }

    /**
     * Create an instance of {@link PARAMETER }
     *
     */
    public PARAMETER createPARAMETER() {
        return new PARAMETER();
    }

    /**
     * Create an instance of {@link STEPPARAMETER }
     *
     */
    public STEPPARAMETER createSTEPPARAMETER() {
        return new STEPPARAMETER();
    }

    /**
     * Create an instance of {@link REFERENCE }
     *
     */
    public REFERENCE createREFERENCE() {
        return new REFERENCE();
    }

    /**
     * Create an instance of {@link STEPS }
     *
     */
    public STEPS createSTEPS() {
        return new STEPS();
    }

    /**
     * Create an instance of {@link BRANCH }
     *
     */
    public BRANCH createBRANCH() {
        return new BRANCH();
    }

    /**
     * Create an instance of {@link IF }
     *
     */
    public IF createIF() {
        return new IF();
    }

    /**
     * Create an instance of {@link ELSEIF }
     *
     */
    public ELSEIF createELSEIF() {
        return new ELSEIF();
    }

    /**
     * Create an instance of {@link ELSE }
     *
     */
    public ELSE createELSE() {
        return new ELSE();
    }

    /**
     * Create an instance of {@link IBELEMENT }
     *
     */
    public IBELEMENT createIBELEMENT() {
        return new IBELEMENT();
    }

    /**
     * Create an instance of {@link LOOPELEMENT }
     *
     */
    public LOOPELEMENT createLOOPELEMENT() {
        return new LOOPELEMENT();
    }

    /**
     * Create an instance of {@link STEPELEMENT }
     *
     */
    public STEPELEMENT createSTEPELEMENT() {
        return new STEPELEMENT();
    }

    /**
     * Create an instance of {@link IMPORTELEMENT }
     *
     */
    public IMPORTELEMENT createIMPORTELEMENT() {
        return new IMPORTELEMENT();
    }

    /**
     * Create an instance of {@link IBIDENTIFIABLE }
     *
     */
    public IBIDENTIFIABLE createIBIDENTIFIABLE() {
        return new IBIDENTIFIABLE();
    }

    /**
     * Create an instance of {@link IBIDENTIFIABLESTRING }
     *
     */
    public IBIDENTIFIABLESTRING createIBIDENTIFIABLESTRING() {
        return new IBIDENTIFIABLESTRING();
    }

    /**
     * Create an instance of {@link STEP }
     *
     */
    public STEP createSTEP() {
        return new STEP();
    }

    /**
     * Create an instance of {@link HMISTEP }
     *
     */
    public HMISTEP createHMISTEP() {
        return new HMISTEP();
    }

    /**
     * Create an instance of {@link DEVICESTEP }
     *
     */
    public DEVICESTEP createDEVICESTEP() {
        return new DEVICESTEP();
    }

    /**
     * Create an instance of {@link DATASTEP }
     *
     */
    public DATASTEP createDATASTEP() {
        return new DATASTEP();
    }

    /**
     * Create an instance of {@link DIAGSERVICE }
     *
     */
    public DIAGSERVICE createDIAGSERVICE() {
        return new DIAGSERVICE();
    }

    /**
     * Create an instance of {@link TIMEPARAMETER }
     *
     */
    public TIMEPARAMETER createTIMEPARAMETER() {
        return new TIMEPARAMETER();
    }

    /**
     * Create an instance of {@link VALUEPROXY }
     *
     */
    public VALUEPROXY createVALUEPROXY() {
        return new VALUEPROXY();
    }

    /**
     * Create an instance of {@link TOLERANCE }
     *
     */
    public TOLERANCE createTOLERANCE() {
        return new TOLERANCE();
    }

    /**
     * Create an instance of {@link DIAGPARAMETERS }
     *
     */
    public DIAGPARAMETERS createDIAGPARAMETERS() {
        return new DIAGPARAMETERS();
    }

    /**
     * Create an instance of {@link DIAGPARAMETER }
     *
     */
    public DIAGPARAMETER createDIAGPARAMETER() {
        return new DIAGPARAMETER();
    }

    /**
     * Create an instance of {@link BLOCKIBNZ }
     *
     */
    public BLOCKIBNZ createBLOCKIBNZ() {
        return new BLOCKIBNZ();
    }

    /**
     * Create an instance of {@link LINKS }
     *
     */
    public LINKS createLINKS() {
        return new LINKS();
    }

    /**
     * Create an instance of {@link LINK }
     *
     */
    public LINK createLINK() {
        return new LINK();
    }

    /**
     * Create an instance of {@link DOCREVISION }
     *
     */
    public DOCREVISION createDOCREVISION() {
        return new DOCREVISION();
    }

    /**
     * Create an instance of {@link DOC }
     *
     */
    public DOC createDOC() {
        return new DOC();
    }

    /**
     * Create an instance of {@link IBVARIANTS }
     *
     */
    public IBVARIANTS createIBVARIANTS() {
        return new IBVARIANTS();
    }

    /**
     * Create an instance of {@link IBVARIANT }
     *
     */
    public IBVARIANT createIBVARIANT() {
        return new IBVARIANT();
    }

    /**
     * Create an instance of {@link REGULATIONS }
     *
     */
    public REGULATIONS createREGULATIONS() {
        return new REGULATIONS();
    }

    /**
     * Create an instance of {@link RELATEDDOCUMENTS }
     *
     */
    public RELATEDDOCUMENTS createRELATEDDOCUMENTS() {
        return new RELATEDDOCUMENTS();
    }

    /**
     * Create an instance of {@link IBOPERATIONS }
     *
     */
    public IBOPERATIONS createIBOPERATIONS() {
        return new IBOPERATIONS();
    }

    /**
     * Create an instance of {@link IBOPERATION }
     *
     */
    public IBOPERATION createIBOPERATION() {
        return new IBOPERATION();
    }

    /**
     * Create an instance of {@link IBDESCRIPTION }
     *
     */
    public IBDESCRIPTION createIBDESCRIPTION() {
        return new IBDESCRIPTION();
    }

    /**
     * Create an instance of {@link SLAVES }
     *
     */
    public SLAVES createSLAVES() {
        return new SLAVES();
    }

    /**
     * Create an instance of {@link SLAVE }
     *
     */
    public SLAVE createSLAVE() {
        return new SLAVE();
    }

    /**
     * Create an instance of {@link IBNZ }
     *
     */
    public IBNZ createIBNZ() {
        return new IBNZ();
    }

    /**
     * Create an instance of {@link CUSTOMERADJUSTMENTS }
     *
     */
    public CUSTOMERADJUSTMENTS createCUSTOMERADJUSTMENTS() {
        return new CUSTOMERADJUSTMENTS();
    }

    /**
     * Create an instance of {@link ADJUSTMENTS }
     *
     */
    public ADJUSTMENTS createADJUSTMENTS() {
        return new ADJUSTMENTS();
    }

    /**
     * Create an instance of {@link DTCS }
     *
     */
    public DTCS createDTCS() {
        return new DTCS();
    }

    /**
     * Create an instance of {@link DTC }
     *
     */
    public DTC createDTC() {
        return new DTC();
    }

    /**
     * Create an instance of {@link POSSIBLEERRORSTATES }
     *
     */
    public POSSIBLEERRORSTATES createPOSSIBLEERRORSTATES() {
        return new POSSIBLEERRORSTATES();
    }

    /**
     * Create an instance of {@link VALIDITIES }
     *
     */
    public VALIDITIES createVALIDITIES() {
        return new VALIDITIES();
    }

    /**
     * Create an instance of {@link VALIDITY }
     *
     */
    public VALIDITY createVALIDITY() {
        return new VALIDITY();
    }

    /**
     * Create an instance of {@link OBJECTIVES }
     *
     */
    public OBJECTIVES createOBJECTIVES() {
        return new OBJECTIVES();
    }

    /**
     * Create an instance of {@link ENVIRONMENT }
     *
     */
    public ENVIRONMENT createENVIRONMENT() {
        return new ENVIRONMENT();
    }

    /**
     * Create an instance of {@link ACCESSAUTHORISATIONS }
     *
     */
    public ACCESSAUTHORISATIONS createACCESSAUTHORISATIONS() {
        return new ACCESSAUTHORISATIONS();
    }

    /**
     * Create an instance of {@link PRODUCTIONMODES }
     *
     */
    public PRODUCTIONMODES createPRODUCTIONMODES() {
        return new PRODUCTIONMODES();
    }

    /**
     * Create an instance of {@link PRODUCTIONMODE }
     *
     */
    public PRODUCTIONMODE createPRODUCTIONMODE() {
        return new PRODUCTIONMODE();
    }

    /**
     * Create an instance of {@link BYTES }
     *
     */
    public BYTES createBYTES() {
        return new BYTES();
    }

    /**
     * Create an instance of {@link ACCESSAUTHORISATION }
     *
     */
    public ACCESSAUTHORISATION createACCESSAUTHORISATION() {
        return new ACCESSAUTHORISATION();
    }

    /**
     * Create an instance of {@link DEPENDENCIES }
     *
     */
    public DEPENDENCIES createDEPENDENCIES() {
        return new DEPENDENCIES();
    }

    /**
     * Create an instance of {@link REPAIRDEPENDENCIES }
     *
     */
    public REPAIRDEPENDENCIES createREPAIRDEPENDENCIES() {
        return new REPAIRDEPENDENCIES();
    }

    /**
     * Create an instance of {@link REPAIRDEPENDENCY }
     *
     */
    public REPAIRDEPENDENCY createREPAIRDEPENDENCY() {
        return new REPAIRDEPENDENCY();
    }

    /**
     * Create an instance of {@link CHANGEDEPENDENCIES }
     *
     */
    public CHANGEDEPENDENCIES createCHANGEDEPENDENCIES() {
        return new CHANGEDEPENDENCIES();
    }

    /**
     * Create an instance of {@link CALIBRATIONDEPENDENCIES }
     *
     */
    public CALIBRATIONDEPENDENCIES createCALIBRATIONDEPENDENCIES() {
        return new CALIBRATIONDEPENDENCIES();
    }

    /**
     * Create an instance of {@link PRECONDITIONS }
     *
     */
    public PRECONDITIONS createPRECONDITIONS() {
        return new PRECONDITIONS();
    }

    /**
     * Create an instance of {@link PRECONDITION }
     *
     */
    public PRECONDITION createPRECONDITION() {
        return new PRECONDITION();
    }

    /**
     * Create an instance of {@link PROCEDURES }
     *
     */
    public PROCEDURES createPROCEDURES() {
        return new PROCEDURES();
    }

    /**
     * Create an instance of {@link PROCEDURE }
     *
     */
    public PROCEDURE createPROCEDURE() {
        return new PROCEDURE();
    }

    /**
     * Create an instance of {@link GROUP }
     *
     */
    public GROUP createGROUP() {
        return new GROUP();
    }

    /**
     * Create an instance of {@link LOOP }
     *
     */
    public LOOP createLOOP() {
        return new LOOP();
    }

    /**
     * Create an instance of {@link SWITCH }
     *
     */
    public SWITCH createSWITCH() {
        return new SWITCH();
    }

    /**
     * Create an instance of {@link CASE }
     *
     */
    public CASE createCASE() {
        return new CASE();
    }

    /**
     * Create an instance of {@link BLOCKS }
     *
     */
    public BLOCKS createBLOCKS() {
        return new BLOCKS();
    }

    /**
     * Create an instance of {@link LOOPBLOCKS }
     *
     */
    public LOOPBLOCKS createLOOPBLOCKS() {
        return new LOOPBLOCKS();
    }

    /**
     * Create an instance of {@link DIAGNOSTICINFOS }
     *
     */
    public DIAGNOSTICINFOS createDIAGNOSTICINFOS() {
        return new DIAGNOSTICINFOS();
    }

    /**
     * Create an instance of {@link DIAGNOSTICINFO }
     *
     */
    public DIAGNOSTICINFO createDIAGNOSTICINFO() {
        return new DIAGNOSTICINFO();
    }

    /**
     * Create an instance of {@link PDX }
     *
     */
    public PDX createPDX() {
        return new PDX();
    }

    /**
     * Create an instance of {@link ODXS }
     *
     */
    public ODXS createODXS() {
        return new ODXS();
    }

    /**
     * Create an instance of {@link ODX }
     *
     */
    public ODX createODX() {
        return new ODX();
    }

    /**
     * Create an instance of {@link BZD }
     *
     */
    public BZD createBZD() {
        return new BZD();
    }

    /**
     * Create an instance of {@link IDENTS }
     *
     */
    public IDENTS createIDENTS() {
        return new IDENTS();
    }

    /**
     * Create an instance of {@link IDENT }
     *
     */
    public IDENT createIDENT() {
        return new IDENT();
    }

    /**
     * Create an instance of {@link SECURITYPROPERTIES }
     *
     */
    public SECURITYPROPERTIES createSECURITYPROPERTIES() {
        return new SECURITYPROPERTIES();
    }

    /**
     * Create an instance of {@link ECU }
     *
     */
    public ECU createECU() {
        return new ECU();
    }

    /**
     * Create an instance of {@link SECURITYPROPERTY }
     *
     */
    public SECURITYPROPERTY createSECURITYPROPERTY() {
        return new SECURITYPROPERTY();
    }

    /**
     * Create an instance of {@link ENTRY }
     *
     */
    public ENTRY createENTRY() {
        return new ENTRY();
    }

    /**
     * Create an instance of {@link REFERENCES }
     *
     */
    public REFERENCES createREFERENCES() {
        return new REFERENCES();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IBLIBRARY }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IBLIBRARY }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "IB-LIBRARY")
    public JAXBElement<IBLIBRARY> createIBLIBRARY(IBLIBRARY value) {
        return new JAXBElement<IBLIBRARY>(_IBLIBRARY_QNAME, IBLIBRARY.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IB1 }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IB1 }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "IB-1")
    public JAXBElement<IB1> createIB1(IB1 value) {
        return new JAXBElement<IB1>(_IB1_QNAME, IB1 .class, null, value);
    }

}
