//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ODX complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ODX"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TYPE" type="{}ODX-TYPE" minOccurs="0"/&gt;
 *         &lt;element name="VARIANT-REF" type="{}REFERENCE" minOccurs="0"/&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ODX", propOrder = {
    "name",
    "type",
    "variantref",
    "desc"
})
public class ODX {

    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "TYPE")
    @XmlSchemaType(name = "string")
    protected ODXTYPE type;
    @XmlElement(name = "VARIANT-REF")
    protected REFERENCE variantref;
    @XmlElement(name = "DESC")
    protected String desc;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ODXTYPE }
     *     
     */
    public ODXTYPE getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ODXTYPE }
     *     
     */
    public void setTYPE(ODXTYPE value) {
        this.type = value;
    }

    /**
     * Gets the value of the variantref property.
     * 
     * @return
     *     possible object is
     *     {@link REFERENCE }
     *     
     */
    public REFERENCE getVARIANTREF() {
        return variantref;
    }

    /**
     * Sets the value of the variantref property.
     * 
     * @param value
     *     allowed object is
     *     {@link REFERENCE }
     *     
     */
    public void setVARIANTREF(REFERENCE value) {
        this.variantref = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC(String value) {
        this.desc = value;
    }

}
