//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PARAMETER-TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PARAMETER-TYPE"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="in"/&gt;
 *     &lt;enumeration value="out"/&gt;
 *     &lt;enumeration value="inout"/&gt;
 *     &lt;enumeration value="context"/&gt;
 *     &lt;enumeration value="state"/&gt;
 *     &lt;enumeration value="variable"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PARAMETER-TYPE")
@XmlEnum
public enum PARAMETERTYPE {

    @XmlEnumValue("in")
    IN("in"),
    @XmlEnumValue("out")
    OUT("out"),
    @XmlEnumValue("inout")
    INOUT("inout"),
    @XmlEnumValue("context")
    CONTEXT("context"),
    @XmlEnumValue("state")
    STATE("state"),
    @XmlEnumValue("variable")
    VARIABLE("variable");
    private final String value;

    PARAMETERTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PARAMETERTYPE fromValue(String v) {
        for (PARAMETERTYPE c: PARAMETERTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
