//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRE-CONDITION complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PRE-CONDITION"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;&gt;IB-IDENTIFIABLE-STRING"&gt;
 *       &lt;attribute name="pRelevant" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="kdRelevant" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRE-CONDITION")
public class PRECONDITION
    extends IBIDENTIFIABLESTRING
{

    @XmlAttribute(name = "pRelevant")
    protected Boolean pRelevant;
    @XmlAttribute(name = "kdRelevant")
    protected Boolean kdRelevant;

    /**
     * Gets the value of the pRelevant property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isPRelevant() {
        if (pRelevant == null) {
            return true;
        } else {
            return pRelevant;
        }
    }

    /**
     * Sets the value of the pRelevant property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPRelevant(Boolean value) {
        this.pRelevant = value;
    }

    /**
     * Gets the value of the kdRelevant property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isKdRelevant() {
        if (kdRelevant == null) {
            return true;
        } else {
            return kdRelevant;
        }
    }

    /**
     * Sets the value of the kdRelevant property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setKdRelevant(Boolean value) {
        this.kdRelevant = value;
    }

}
