//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PRODUCTION-MODE complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PRODUCTION-MODE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}IB-ELEMENT"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *         &lt;element name="BYTES" type="{}BYTES" minOccurs="0"/&gt;
 *         &lt;element name="VARIANTS" type="{}VARIANTS" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PRODUCTION-MODE", propOrder = {
    "desc",
    "bytes",
    "variants"
})
public class PRODUCTIONMODE
    extends IBELEMENT
{

    @XmlElement(name = "DESC")
    protected String desc;
    @XmlElement(name = "BYTES")
    protected BYTES bytes;
    @XmlElement(name = "VARIANTS")
    protected VARIANTS variants;

    /**
     * Gets the value of the desc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDESC(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the bytes property.
     *
     * @return
     *     possible object is
     *     {@link BYTES }
     *
     */
    public BYTES getBYTES() {
        return bytes;
    }

    /**
     * Sets the value of the bytes property.
     *
     * @param value
     *     allowed object is
     *     {@link BYTES }
     *
     */
    public void setBYTES(BYTES value) {
        this.bytes = value;
    }

    /**
     * Gets the value of the variants property.
     *
     * @return
     *     possible object is
     *     {@link VARIANTS }
     *
     */
    public VARIANTS getVARIANTS() {
        return variants;
    }

    /**
     * Sets the value of the variants property.
     *
     * @param value
     *     allowed object is
     *     {@link VARIANTS }
     *
     */
    public void setVARIANTS(VARIANTS value) {
        this.variants = value;
    }

}
