//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REFERENCES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REFERENCES"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="REGULATIONS" type="{}REGULATIONS" minOccurs="0"/&gt;
 *         &lt;element name="RELATED-DOCUMENTS" type="{}RELATED-DOCUMENTS" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REFERENCES", propOrder = {
    "regulations",
    "relateddocuments"
})
public class REFERENCES {

    @XmlElement(name = "REGULATIONS")
    protected REGULATIONS regulations;
    @XmlElement(name = "RELATED-DOCUMENTS")
    protected RELATEDDOCUMENTS relateddocuments;

    /**
     * Gets the value of the regulations property.
     * 
     * @return
     *     possible object is
     *     {@link REGULATIONS }
     *     
     */
    public REGULATIONS getREGULATIONS() {
        return regulations;
    }

    /**
     * Sets the value of the regulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link REGULATIONS }
     *     
     */
    public void setREGULATIONS(REGULATIONS value) {
        this.regulations = value;
    }

    /**
     * Gets the value of the relateddocuments property.
     * 
     * @return
     *     possible object is
     *     {@link RELATEDDOCUMENTS }
     *     
     */
    public RELATEDDOCUMENTS getRELATEDDOCUMENTS() {
        return relateddocuments;
    }

    /**
     * Sets the value of the relateddocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link RELATEDDOCUMENTS }
     *     
     */
    public void setRELATEDDOCUMENTS(RELATEDDOCUMENTS value) {
        this.relateddocuments = value;
    }

}
