//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for STEPS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STEPS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="STEP" type="{}STEP"/&gt;
 *         &lt;element name="HMI-STEP" type="{}HMI-STEP"/&gt;
 *         &lt;element name="DEVICE-STEP" type="{}DEVICE-STEP"/&gt;
 *         &lt;element name="DATA-STEP" type="{}DATA-STEP"/&gt;
 *         &lt;element name="BRANCH" type="{}BRANCH"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STEPS", propOrder = {
    "stepOrHMISTEPOrDEVICESTEP"
})
public class STEPS {

    @XmlElements({
        @XmlElement(name = "STEP", type = STEP.class),
        @XmlElement(name = "HMI-STEP", type = HMISTEP.class),
        @XmlElement(name = "DEVICE-STEP", type = DEVICESTEP.class),
        @XmlElement(name = "DATA-STEP", type = DATASTEP.class),
        @XmlElement(name = "BRANCH", type = BRANCH.class)
    })
    protected List<Object> stepOrHMISTEPOrDEVICESTEP;

    /**
     * Gets the value of the stepOrHMISTEPOrDEVICESTEP property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stepOrHMISTEPOrDEVICESTEP property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTEPOrHMISTEPOrDEVICESTEP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STEP }
     * {@link HMISTEP }
     * {@link DEVICESTEP }
     * {@link DATASTEP }
     * {@link BRANCH }
     * 
     * 
     */
    public List<Object> getSTEPOrHMISTEPOrDEVICESTEP() {
        if (stepOrHMISTEPOrDEVICESTEP == null) {
            stepOrHMISTEPOrDEVICESTEP = new ArrayList<Object>();
        }
        return this.stepOrHMISTEPOrDEVICESTEP;
    }

}
