//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TIME-PARAMETER complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TIME-PARAMETER"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *         &lt;element name="VALUE-PROXY" type="{}VALUE-PROXY" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TIME-PARAMETER", propOrder = {
    "desc",
    "valueproxy"
})
public class TIMEPARAMETER {

    @XmlElement(name = "DESC")
    protected String desc;
    @XmlElement(name = "VALUE-PROXY")
    protected VALUEPROXY valueproxy;

    /**
     * Gets the value of the desc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDESC(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the valueproxy property.
     *
     * @return
     *     possible object is
     *     {@link VALUEPROXY }
     *
     */
    public VALUEPROXY getVALUEPROXY() {
        return valueproxy;
    }

    /**
     * Sets the value of the valueproxy property.
     *
     * @param value
     *     allowed object is
     *     {@link VALUEPROXY }
     *
     */
    public void setVALUEPROXY(VALUEPROXY value) {
        this.valueproxy = value;
    }

}
