//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for VALIDITIES complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VALIDITIES"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VALIDITY" type="{}VALIDITY" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="exporttime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VALIDITIES", propOrder = {
    "validity"
})
public class VALIDITIES {

    @XmlElement(name = "VALIDITY", required = true)
    protected List<VALIDITY> validity;
    @XmlAttribute(name = "exporttime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar exporttime;

    /**
     * Gets the value of the validity property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validity property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVALIDITY().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VALIDITY }
     *
     *
     */
    public List<VALIDITY> getVALIDITY() {
        if (validity == null) {
            validity = new ArrayList<VALIDITY>();
        }
        return this.validity;
    }

    /**
     * Gets the value of the exporttime property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getExporttime() {
        return exporttime;
    }

    /**
     * Sets the value of the exporttime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setExporttime(XMLGregorianCalendar value) {
        this.exporttime = value;
    }

}
