//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.29 at 04:51:57 PM EEST 
//


package com.vw.ipppdiffer.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VALIDITY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VALIDITY"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PRODUCT-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VEHICLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ODX-PLATFORM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PART-NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="F-TAB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SUPPLIER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LAUNCH-DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="END-DATE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DESC" type="{}DESC" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VALIDITY", propOrder = {
    "productid",
    "vehicle",
    "odxplatform",
    "partnumber",
    "ftab",
    "supplier",
    "launchdate",
    "enddate",
    "desc"
})
public class VALIDITY {

    @XmlElement(name = "PRODUCT-ID")
    protected String productid;
    @XmlElement(name = "VEHICLE")
    protected String vehicle;
    @XmlElement(name = "ODX-PLATFORM")
    protected String odxplatform;
    @XmlElement(name = "PART-NUMBER", required = true)
    protected String partnumber;
    @XmlElement(name = "F-TAB")
    protected String ftab;
    @XmlElement(name = "SUPPLIER")
    protected String supplier;
    @XmlElement(name = "LAUNCH-DATE")
    protected String launchdate;
    @XmlElement(name = "END-DATE")
    protected String enddate;
    @XmlElement(name = "DESC")
    protected String desc;

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTID(String value) {
        this.productid = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVEHICLE() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVEHICLE(String value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the odxplatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getODXPLATFORM() {
        return odxplatform;
    }

    /**
     * Sets the value of the odxplatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setODXPLATFORM(String value) {
        this.odxplatform = value;
    }

    /**
     * Gets the value of the partnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTNUMBER() {
        return partnumber;
    }

    /**
     * Sets the value of the partnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTNUMBER(String value) {
        this.partnumber = value;
    }

    /**
     * Gets the value of the ftab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFTAB() {
        return ftab;
    }

    /**
     * Sets the value of the ftab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFTAB(String value) {
        this.ftab = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPLIER() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPLIER(String value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the launchdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLAUNCHDATE() {
        return launchdate;
    }

    /**
     * Sets the value of the launchdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLAUNCHDATE(String value) {
        this.launchdate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENDDATE() {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENDDATE(String value) {
        this.enddate = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESC() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESC(String value) {
        this.desc = value;
    }

}
